version: "3.9"

services:
  mysql:
    image: mysql:latest
    restart: on-failure
    volumes:
      - mysql-volume-1:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      # remove the password from the file or remove the file from git
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - encyclopedia-network

  backend:
    image: thisisnothappening/nodejs-encyclopedia-project:latest
    pull_policy: always
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - encyclopedia-network
    depends_on:
      - mysql

  frontend:
    image: thisisnothappening/reactjs-encyclopedia-project:latest
    pull_policy: always
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_HOST_NAME=http://localhost:8080
    networks:
      - encyclopedia-network
    depends_on:
      - backend

volumes:
  mysql-volume-1:
    external: true

networks:
  encyclopedia-network:
    external: true
