FROM jenkins/agent:alpine-jdk11

USER root

RUN apk update

RUN apk add --no-cache nodejs npm docker-cli

ENV BUILDX_VERSION 0.11.1
RUN mkdir -p ~/.docker/cli-plugins && \
    wget -q -O ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v${BUILDX_VERSION}/buildx-v${BUILDX_VERSION}.linux-amd64 && \
    chmod a+x ~/.docker/cli-plugins/docker-buildx
