FROM jenkins/agent:alpine-jdk11

USER root

RUN apk update

RUN apk add --no-cache nodejs npm docker-cli python3 py3-pip

ENV BUILDX_VERSION 0.11.1
RUN mkdir -p ~/.docker/cli-plugins && \
    wget -q -O ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v${BUILDX_VERSION}/buildx-v${BUILDX_VERSION}.linux-amd64 && \
    chmod a+x ~/.docker/cli-plugins/docker-buildx

RUN pip3 install --upgrade awscli

ENV JMETER_VERSION 5.6
RUN wget -q https://downloads.apache.org/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz && \
    tar -xzf apache-jmeter-${JMETER_VERSION}.tgz -C /opt && \
    rm apache-jmeter-${JMETER_VERSION}.tgz

ENV JMETER_HOME /opt/apache-jmeter-${JMETER_VERSION}
ENV PATH $JMETER_HOME/bin:$PATH
